language: php

services:
  - docker

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - GEOSERVER_URL="http://127.0.0.1:8600/geoserver/"
    - GEOSERVER_USER="admin"
    - GEOSERVER_PASSWORD="geoserver"
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"
    - COMPOSER_FLAGS="--prefer-stable" GEOSERVER_TAG="2.15.2"

matrix:
  exclude:
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - sudo service mysql stop
  - docker-compose -f ./tests/docker-compose.yml up -d
  - php ./tests/wait.php

script:
  - ./vendor/bin/parallel-lint --exclude vendor .
  - ./vendor/bin/phpunit

after_script:
  - docker-compose -f ./tests/docker-compose.yml down
